import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const ibmPlexSansThai = IBM_Plex_Sans_Thai({ 
  subsets: ["thai", "latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ibmPlexSansThai.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
